"""
Script para popular a base de dados com Praias Fluviais e Piscinas Naturais de Portugal
"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
from pathlib import Path
import os
import uuid
from datetime import datetime, timezone

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# MongoDB connection
mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

# Descrição geral da categoria
PISCINAS_CATEGORY_DESCRIPTION = """
As praias fluviais são uma alternativa às praias do mar e são geralmente formadas por áreas com areia ou pedra nas margens dos rios ou lagos, onde as pessoas podem tomar banho, relaxar ou praticar atividades aquáticas. Além disso, as praias fluviais são normalmente rodeadas por uma paisagem natural, como montanhas, florestas e vales, o que proporciona um ambiente agradável e tranquilo.

Algumas das vantagens das praias fluviais incluem águas mais calmas e menos salgadas em comparação com o mar, o que torna o banho mais agradável para algumas pessoas, especialmente crianças e idosos. Além disso, muitas praias fluviais são vigiadas por salva-vidas durante o verão, tornando-as mais seguras para os banhistas.

Em Portugal, as praias fluviais são bastante populares e há várias opções por todo o país - desde o Minho ao Algarve, passando pelas serras do Centro. As praias fluviais são uma excelente opção para quem quer desfrutar de um dia de sol e de água em um ambiente mais tranquilo e natural.
"""

# Dados das Praias Fluviais organizados por distrito/região
PISCINAS_DATA = [
    # ==========================================
    # DISTRITO DE AVEIRO
    # ==========================================
    {"name": "Praia Fluvial de Burgães", "description": "Praia fluvial acessível a todos com classificação de água balnear, localizada em Vale de Cambra.", "region": "norte", "address": "Vale de Cambra, Aveiro", "location": {"lat": 40.8500, "lng": -8.3833}, "tags": ["acessível", "água balnear", "Aveiro"], "metadata": {"district": "Aveiro", "municipality": "Vale de Cambra", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial da Pontemieiro", "description": "Praia fluvial com classificação de água balnear em Vale de Cambra.", "region": "norte", "address": "Vale de Cambra, Aveiro", "location": {"lat": 40.8400, "lng": -8.3700}, "tags": ["água balnear", "Aveiro"], "metadata": {"district": "Aveiro", "municipality": "Vale de Cambra", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial Paço Mato-Viadal", "description": "Praia fluvial com classificação de água balnear em Vale de Cambra.", "region": "norte", "address": "Vale de Cambra, Aveiro", "location": {"lat": 40.8450, "lng": -8.3650}, "tags": ["água balnear", "Aveiro"], "metadata": {"district": "Aveiro", "municipality": "Vale de Cambra", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial Quinta do Barco", "description": "Praia fluvial premiada com Bandeira Azul, acessível a todos e com classificação de água balnear. Uma das mais completas da região.", "region": "norte", "address": "Sever do Vouga, Aveiro", "location": {"lat": 40.7083, "lng": -8.3608}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Aveiro", "premiada"], "metadata": {"district": "Aveiro", "municipality": "Sever do Vouga", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Cascata da Cabreia", "description": "Praia fluvial junto a uma impressionante cascata, com classificação de água balnear. Paisagem deslumbrante na Serra da Freita.", "region": "norte", "address": "Sever do Vouga, Aveiro", "location": {"lat": 40.7525, "lng": -8.3905}, "tags": ["cascata", "água balnear", "Aveiro", "Serra da Freita"], "metadata": {"district": "Aveiro", "municipality": "Sever do Vouga", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Mizarela", "description": "Praia fluvial na Serra da Freita com classificação de água balnear e paisagem montanhosa única.", "region": "norte", "address": "Arouca, Aveiro", "location": {"lat": 40.8833, "lng": -8.2500}, "tags": ["Serra da Freita", "água balnear", "Arouca"], "metadata": {"district": "Aveiro", "municipality": "Arouca", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial do Areinho", "description": "Praia fluvial com qualidade de ouro, acessível a todos e classificação de água balnear. Uma das melhores de Arouca.", "region": "norte", "address": "Arouca, Aveiro", "location": {"lat": 40.9333, "lng": -8.2667}, "tags": ["qualidade ouro", "acessível", "água balnear", "Arouca"], "metadata": {"district": "Aveiro", "municipality": "Arouca", "certifications": ["Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial da Espiunca", "description": "Praia fluvial em Arouca, num ambiente natural preservado junto ao Rio Paiva.", "region": "norte", "address": "Arouca, Aveiro", "location": {"lat": 40.9500, "lng": -8.1833}, "tags": ["Rio Paiva", "natureza", "Arouca"], "metadata": {"district": "Aveiro", "municipality": "Arouca"}},
    {"name": "Praia Fluvial do Vau", "description": "Praia fluvial em Arouca com águas cristalinas e envolvência natural.", "region": "norte", "address": "Arouca, Aveiro", "location": {"lat": 40.9400, "lng": -8.2000}, "tags": ["natureza", "Arouca"], "metadata": {"district": "Aveiro", "municipality": "Arouca"}},
    {"name": "Praia Fluvial da Várzea", "description": "Praia fluvial em Castelo de Paiva junto ao Rio Douro.", "region": "norte", "address": "Bairros, Castelo de Paiva, Aveiro", "location": {"lat": 41.0500, "lng": -8.2667}, "tags": ["Rio Douro", "Castelo de Paiva"], "metadata": {"district": "Aveiro", "municipality": "Castelo de Paiva"}},
    {"name": "Praia Fluvial de Pedorido Choupal", "description": "Praia fluvial com classificação de água balnear em Castelo de Paiva.", "region": "norte", "address": "Castelo de Paiva, Aveiro", "location": {"lat": 41.0333, "lng": -8.2500}, "tags": ["água balnear", "Castelo de Paiva"], "metadata": {"district": "Aveiro", "municipality": "Castelo de Paiva", "certifications": ["Água Balnear"]}},
    {"name": "Piscina Fluvial de Águeda", "description": "Piscina fluvial com classificação de água balnear na cidade de Águeda.", "region": "norte", "address": "Águeda, Aveiro", "location": {"lat": 40.5767, "lng": -8.4478}, "tags": ["piscina", "água balnear", "Águeda"], "metadata": {"district": "Aveiro", "municipality": "Águeda", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Bolfiar", "description": "Praia fluvial com classificação de água balnear em Águeda.", "region": "norte", "address": "Águeda, Aveiro", "location": {"lat": 40.5500, "lng": -8.4333}, "tags": ["água balnear", "Águeda"], "metadata": {"district": "Aveiro", "municipality": "Águeda", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial do Alfusqueiro", "description": "Praia fluvial com classificação de água balnear, localizada numa zona de grande beleza natural em Águeda.", "region": "norte", "address": "Águeda, Aveiro", "location": {"lat": 40.6267, "lng": -8.3600}, "tags": ["água balnear", "natureza", "Águeda"], "metadata": {"district": "Aveiro", "municipality": "Águeda", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Mâmoa", "description": "Praia fluvial premiada com Bandeira Azul e classificação de água balnear em Santa Maria da Feira.", "region": "norte", "address": "Milheirós de Poiares, Santa Maria da Feira, Aveiro", "location": {"lat": 40.9667, "lng": -8.4833}, "tags": ["Bandeira Azul", "água balnear", "Santa Maria da Feira"], "metadata": {"district": "Aveiro", "municipality": "Santa Maria da Feira", "certifications": ["Bandeira Azul", "Água Balnear"]}},

    # ==========================================
    # DISTRITO DE BRAGA
    # ==========================================
    {"name": "Praia Fluvial de São Paio Merelim", "description": "Praia fluvial acessível a todos com classificação de água balnear em Braga.", "region": "norte", "address": "São Paio Merelim, Braga", "location": {"lat": 41.5500, "lng": -8.4000}, "tags": ["acessível", "água balnear", "Braga"], "metadata": {"district": "Braga", "municipality": "Braga", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Adaúfe", "description": "Uma das praias fluviais mais completas do Minho, com Bandeira Azul, acessível a todos e água balnear de excelência.", "region": "norte", "address": "Adaúfe, Braga", "location": {"lat": 41.6092, "lng": -8.4078}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Braga", "Minho"], "metadata": {"district": "Braga", "municipality": "Braga", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"], "gps": "41.5782, -8.3943"}},
    {"name": "Praia Fluvial da Ponte do Bico", "description": "Praia fluvial com classificação de água balnear em Palmeira, Braga.", "region": "norte", "address": "Palmeira, Braga", "location": {"lat": 41.5667, "lng": -8.3500}, "tags": ["água balnear", "Braga"], "metadata": {"district": "Braga", "municipality": "Braga", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial do Cavadinho", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Crespos.", "region": "norte", "address": "Crespos, Braga", "location": {"lat": 41.5833, "lng": -8.3667}, "tags": ["qualidade ouro", "água balnear", "Braga"], "metadata": {"district": "Braga", "municipality": "Braga", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial de Navarra", "description": "Praia fluvial com classificação de água balnear em Santa Lucrécia de Algeriz e Navarra.", "region": "norte", "address": "Navarra, Braga", "location": {"lat": 41.6000, "lng": -8.3833}, "tags": ["água balnear", "Braga"], "metadata": {"district": "Braga", "municipality": "Braga", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Loureira", "description": "Praia fluvial com classificação de água balnear em Vila Verde.", "region": "norte", "address": "Vila Verde, Braga", "location": {"lat": 41.6500, "lng": -8.4333}, "tags": ["água balnear", "Vila Verde"], "metadata": {"district": "Braga", "municipality": "Vila Verde", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Prado Faial", "description": "Praia fluvial com classificação de água balnear em Vila Verde.", "region": "norte", "address": "Vila Verde, Braga", "location": {"lat": 41.5986, "lng": -8.4581}, "tags": ["água balnear", "Vila Verde"], "metadata": {"district": "Braga", "municipality": "Vila Verde", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Felinhos", "description": "Praia fluvial com classificação de água balnear em Lago, Amares.", "region": "norte", "address": "Lago, Amares, Braga", "location": {"lat": 41.6333, "lng": -8.3500}, "tags": ["água balnear", "Amares"], "metadata": {"district": "Braga", "municipality": "Amares", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Palmeira", "description": "Praia fluvial com classificação de água balnear em Entre-Pontes, Amares.", "region": "norte", "address": "Entre-Pontes, Amares, Braga", "location": {"lat": 41.6167, "lng": -8.3333}, "tags": ["água balnear", "Amares"], "metadata": {"district": "Braga", "municipality": "Amares", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial das Taipas", "description": "Praia fluvial junto às famosas Termas das Caldas das Taipas em Guimarães.", "region": "norte", "address": "Caldelas, Guimarães, Braga", "location": {"lat": 41.5167, "lng": -8.4000}, "tags": ["Guimarães", "termas"], "metadata": {"district": "Braga", "municipality": "Guimarães"}},
    {"name": "Praia Fluvial Praia Seca", "description": "Praia fluvial com classificação de água balnear em Caldelas, Guimarães.", "region": "norte", "address": "Caldelas, Guimarães, Braga", "location": {"lat": 41.5200, "lng": -8.4050}, "tags": ["água balnear", "Guimarães"], "metadata": {"district": "Braga", "municipality": "Guimarães", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Alqueirão", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear no coração do Gerês.", "region": "norte", "address": "Gerês, Terras de Bouro, Braga", "location": {"lat": 41.6792, "lng": -8.1763}, "tags": ["qualidade ouro", "água balnear", "Gerês", "Parque Nacional"], "metadata": {"district": "Braga", "municipality": "Terras de Bouro", "certifications": ["Qualidade de Ouro", "Água Balnear"], "gps": "41°40'45.2\"N 8°10'34.6\"W"}},
    {"name": "Praia Fluvial Albufeira do Gerês", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear na albufeira do Gerês. Paisagem deslumbrante.", "region": "norte", "address": "Terras de Bouro, Braga", "location": {"lat": 41.7000, "lng": -8.1500}, "tags": ["qualidade ouro", "água balnear", "Gerês", "albufeira"], "metadata": {"district": "Braga", "municipality": "Terras de Bouro", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial da Barca", "description": "Praia fluvial com classificação de água balnear em Terras de Bouro.", "region": "norte", "address": "Terras de Bouro, Braga", "location": {"lat": 41.7167, "lng": -8.1667}, "tags": ["água balnear", "Gerês"], "metadata": {"district": "Braga", "municipality": "Terras de Bouro", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Vilarinho das Furnas", "description": "Praia fluvial histórica no Gerês, junto às ruínas da antiga aldeia submersa de Vilarinho das Furnas.", "region": "norte", "address": "Terras de Bouro, Braga", "location": {"lat": 41.7333, "lng": -8.1333}, "tags": ["histórica", "Gerês", "aldeia submersa"], "metadata": {"district": "Braga", "municipality": "Terras de Bouro"}},
    {"name": "Praia Fluvial de Brufe", "description": "Praia fluvial no Gerês com ambiente selvagem e águas cristalinas.", "region": "norte", "address": "Terras de Bouro, Braga", "location": {"lat": 41.7500, "lng": -8.1500}, "tags": ["Gerês", "selvagem"], "metadata": {"district": "Braga", "municipality": "Terras de Bouro"}},
    {"name": "Praia Fluvial do Rio Homem", "description": "Praia fluvial junto ao Rio Homem no Parque Nacional Peneda-Gerês.", "region": "norte", "address": "Terras de Bouro, Braga", "location": {"lat": 41.7400, "lng": -8.1600}, "tags": ["Rio Homem", "Gerês", "Parque Nacional"], "metadata": {"district": "Braga", "municipality": "Terras de Bouro"}},
    {"name": "Praia Fluvial do México", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Vieira do Minho.", "region": "norte", "address": "Vieira do Minho, Braga", "location": {"lat": 41.6333, "lng": -8.1333}, "tags": ["qualidade ouro", "água balnear", "Vieira do Minho"], "metadata": {"district": "Braga", "municipality": "Vieira do Minho", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Albufeira do Ermal", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear na albufeira do Ermal.", "region": "norte", "address": "Vieira do Minho, Braga", "location": {"lat": 41.5942, "lng": -8.1302}, "tags": ["qualidade ouro", "água balnear", "albufeira", "Vieira do Minho"], "metadata": {"district": "Braga", "municipality": "Vieira do Minho", "certifications": ["Qualidade de Ouro", "Água Balnear"], "gps": "41°35'39.1\"N 8°07'48.8\"W"}},
    {"name": "Praia Fluvial de Verim", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Póvoa de Lanhoso.", "region": "norte", "address": "Póvoa de Lanhoso, Braga", "location": {"lat": 41.5667, "lng": -8.2667}, "tags": ["qualidade ouro", "água balnear", "Póvoa de Lanhoso"], "metadata": {"district": "Braga", "municipality": "Póvoa de Lanhoso", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial da Rola", "description": "Praia fluvial com classificação de água balnear em Taíde, Póvoa de Lanhoso.", "region": "norte", "address": "Taíde, Póvoa de Lanhoso, Braga", "location": {"lat": 41.5500, "lng": -8.2500}, "tags": ["água balnear", "Póvoa de Lanhoso"], "metadata": {"district": "Braga", "municipality": "Póvoa de Lanhoso", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Cavez", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Cabeceiras de Basto.", "region": "norte", "address": "Cabeceiras de Basto, Braga", "location": {"lat": 41.5162, "lng": -7.8900}, "tags": ["qualidade ouro", "água balnear", "Cabeceiras de Basto"], "metadata": {"district": "Braga", "municipality": "Cabeceiras de Basto", "certifications": ["Qualidade de Ouro", "Água Balnear"], "gps": "41°30'58.2\"N 7°53'24.0\"W"}},
    {"name": "Praia Fluvial da Ponte Ranha", "description": "Praia fluvial com classificação de água balnear em Cabeceiras de Basto.", "region": "norte", "address": "Cabeceiras de Basto, Braga", "location": {"lat": 41.5000, "lng": -7.9000}, "tags": ["água balnear", "Cabeceiras de Basto"], "metadata": {"district": "Braga", "municipality": "Cabeceiras de Basto", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial Fermil de Basto", "description": "Praia fluvial com classificação de água balnear em Celorico de Basto.", "region": "norte", "address": "Celorico de Basto, Braga", "location": {"lat": 41.4000, "lng": -8.0000}, "tags": ["água balnear", "Celorico de Basto"], "metadata": {"district": "Braga", "municipality": "Celorico de Basto", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Albufeira da Queimadela", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro, acessível a todos e com classificação de água balnear. Uma das melhores do Norte.", "region": "norte", "address": "Fafe, Braga", "location": {"lat": 41.5978, "lng": -8.4581}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Fafe", "premiada"], "metadata": {"district": "Braga", "municipality": "Fafe", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "41°35'51.9\"N 8°27'29.3\"W"}},

    # ==========================================
    # DISTRITO DE BRAGANÇA
    # ==========================================
    {"name": "Praia Fluvial da Ponte do Rio Baceiro", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Parâmio, Bragança.", "region": "norte", "address": "Parâmio, Bragança", "location": {"lat": 41.8000, "lng": -6.7000}, "tags": ["qualidade ouro", "água balnear", "Bragança"], "metadata": {"district": "Bragança", "municipality": "Bragança", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial da Congida", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro, acessível a todos em Freixo de Espada à Cinta.", "region": "norte", "address": "Freixo de Espada à Cinta, Bragança", "location": {"lat": 41.0833, "lng": -6.8167}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Douro"], "metadata": {"district": "Bragança", "municipality": "Freixo de Espada à Cinta", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Fraga da Pegada", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Macedo de Cavaleiros.", "region": "norte", "address": "Macedo de Cavaleiros, Bragança", "location": {"lat": 41.5858, "lng": -6.9067}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Azibo"], "metadata": {"district": "Bragança", "municipality": "Macedo de Cavaleiros", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Azibo", "description": "Praia fluvial com qualidade de ouro e acessível a todos na Albufeira do Azibo. Uma das mais bonitas de Trás-os-Montes.", "region": "norte", "address": "Macedo de Cavaleiros, Bragança", "location": {"lat": 41.5860, "lng": -6.9067}, "tags": ["qualidade ouro", "acessível", "água balnear", "Azibo", "albufeira"], "metadata": {"district": "Bragança", "municipality": "Macedo de Cavaleiros", "certifications": ["Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "41°35'09.6\"N 6°54'24.0\"W"}},
    {"name": "Praia Fluvial Parque Dr José Gama", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Mirandela.", "region": "norte", "address": "Mirandela, Bragança", "location": {"lat": 41.4833, "lng": -7.1833}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Mirandela"], "metadata": {"district": "Bragança", "municipality": "Mirandela", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Maravilha", "description": "Praia fluvial com classificação de água balnear em Mirandela.", "region": "norte", "address": "Mirandela, Bragança", "location": {"lat": 41.4900, "lng": -7.2000}, "tags": ["água balnear", "Mirandela"], "metadata": {"district": "Bragança", "municipality": "Mirandela", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial Ponte Frades", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Vinhais.", "region": "norte", "address": "Vinhais, Bragança", "location": {"lat": 41.8333, "lng": -7.0000}, "tags": ["qualidade ouro", "água balnear", "Vinhais"], "metadata": {"district": "Bragança", "municipality": "Vinhais", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Ponte da Arranca", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Vinhais.", "region": "norte", "address": "Vinhais, Bragança", "location": {"lat": 41.8500, "lng": -7.0167}, "tags": ["qualidade ouro", "água balnear", "Vinhais"], "metadata": {"district": "Bragança", "municipality": "Vinhais", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Ponte da Soeira", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Vinhais.", "region": "norte", "address": "Vinhais, Bragança", "location": {"lat": 41.8400, "lng": -7.0100}, "tags": ["qualidade ouro", "água balnear", "Vinhais"], "metadata": {"district": "Bragança", "municipality": "Vinhais", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Foz Rio Sabor", "description": "Praia fluvial com classificação de água balnear na foz do Rio Sabor, Torre de Moncorvo.", "region": "norte", "address": "Torre de Moncorvo, Bragança", "location": {"lat": 41.1667, "lng": -7.0500}, "tags": ["água balnear", "Rio Sabor", "Torre de Moncorvo"], "metadata": {"district": "Bragança", "municipality": "Torre de Moncorvo", "certifications": ["Água Balnear"]}},

    # ==========================================
    # DISTRITO DO PORTO
    # ==========================================
    {"name": "Praia Fluvial de Bitetos", "description": "Praia fluvial acessível a todos com classificação de água balnear em Marco de Canaveses.", "region": "norte", "address": "Várzea do Douro, Marco de Canaveses, Porto", "location": {"lat": 41.1210, "lng": -8.1583}, "tags": ["acessível", "água balnear", "Marco de Canaveses", "Rio Douro"], "metadata": {"district": "Porto", "municipality": "Marco de Canaveses", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial da Lomba", "description": "Praia fluvial acessível a todos com classificação de água balnear em Gondomar.", "region": "norte", "address": "Gondomar, Porto", "location": {"lat": 41.0695, "lng": -8.4121}, "tags": ["acessível", "água balnear", "Gondomar", "Rio Douro"], "metadata": {"district": "Porto", "municipality": "Gondomar", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Vila Meã", "description": "Praia fluvial acessível a todos com classificação de água balnear no Rio Odres, Amarante.", "region": "norte", "address": "Vila Meã, Amarante, Porto", "location": {"lat": 41.2667, "lng": -8.0833}, "tags": ["acessível", "água balnear", "Amarante", "Rio Odres"], "metadata": {"district": "Porto", "municipality": "Amarante", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Lagoa de Freixo de Baixo", "description": "Praia fluvial com classificação de água balnear na lagoa de Freixo de Baixo, Amarante.", "region": "norte", "address": "Freixo de Baixo, Amarante, Porto", "location": {"lat": 41.2500, "lng": -8.0667}, "tags": ["água balnear", "lagoa", "Amarante"], "metadata": {"district": "Porto", "municipality": "Amarante", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Zebreiros", "description": "Praia fluvial acessível a todos com classificação de água balnear em Gondomar.", "region": "norte", "address": "Zebreiros, Gondomar, Porto", "location": {"lat": 41.1063, "lng": -8.4876}, "tags": ["acessível", "água balnear", "Gondomar"], "metadata": {"district": "Porto", "municipality": "Gondomar", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Luzim", "description": "Praia fluvial em Penafiel com ambiente tranquilo.", "region": "norte", "address": "Luzim, Penafiel, Porto", "location": {"lat": 41.1115, "lng": -8.2246}, "tags": ["Penafiel"], "metadata": {"district": "Porto", "municipality": "Penafiel"}},
    {"name": "Praia Fluvial de Crestuma", "description": "Praia fluvial junto ao Rio Douro em Vila Nova de Gaia.", "region": "norte", "address": "Crestuma, Vila Nova de Gaia, Porto", "location": {"lat": 41.0688, "lng": -8.5028}, "tags": ["Rio Douro", "Vila Nova de Gaia"], "metadata": {"district": "Porto", "municipality": "Vila Nova de Gaia", "gps": "41°04'07.8\"N 8°30'10.2\"W"}},

    # ==========================================
    # DISTRITO DE VIANA DO CASTELO
    # ==========================================
    {"name": "Praia Fluvial das Azenhas", "description": "Praia fluvial com classificação de água balnear em Vilar de Mouros, Caminha.", "region": "norte", "address": "Vilar de Mouros, Caminha, Viana do Castelo", "location": {"lat": 41.8889, "lng": -8.7833}, "tags": ["água balnear", "Caminha", "Minho"], "metadata": {"district": "Viana do Castelo", "municipality": "Caminha", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial Lenta", "description": "Praia fluvial com classificação de água balnear em Vila Nova de Cerveira.", "region": "norte", "address": "Vila Nova de Cerveira, Viana do Castelo", "location": {"lat": 41.9333, "lng": -8.7333}, "tags": ["água balnear", "Vila Nova de Cerveira"], "metadata": {"district": "Viana do Castelo", "municipality": "Vila Nova de Cerveira", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Ponte da Barca", "description": "Praia fluvial acessível a todos com classificação de água balnear junto à histórica ponte medieval.", "region": "norte", "address": "Ponte da Barca, Viana do Castelo", "location": {"lat": 41.8069, "lng": -8.4186}, "tags": ["acessível", "água balnear", "Ponte da Barca", "histórico"], "metadata": {"district": "Viana do Castelo", "municipality": "Ponte da Barca", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Taboão", "description": "Praia fluvial em Paredes de Coura, no coração do Alto Minho.", "region": "norte", "address": "Paredes de Coura, Viana do Castelo", "location": {"lat": 42.0372, "lng": -8.5024}, "tags": ["Paredes de Coura", "Alto Minho"], "metadata": {"district": "Viana do Castelo", "municipality": "Paredes de Coura", "gps": "42°02'13.9\"N 8°30'08.8\"W"}},
    {"name": "Praia Fluvial de Pontilhão da Valeta", "description": "Praia fluvial com classificação de água balnear em Arcos de Valdevez.", "region": "norte", "address": "Arcos de Valdevez, Viana do Castelo", "location": {"lat": 41.8486, "lng": -8.4191}, "tags": ["água balnear", "Arcos de Valdevez"], "metadata": {"district": "Viana do Castelo", "municipality": "Arcos de Valdevez", "certifications": ["Água Balnear"], "gps": "41°50'55.9\"N 8°25'08.8\"W"}},
    {"name": "Praia Fluvial do Arnado", "description": "Praia fluvial em Ponte de Lima, junto ao Rio Lima.", "region": "norte", "address": "Ponte de Lima, Viana do Castelo", "location": {"lat": 41.7667, "lng": -8.5833}, "tags": ["Rio Lima", "Ponte de Lima"], "metadata": {"district": "Viana do Castelo", "municipality": "Ponte de Lima"}},

    # ==========================================
    # DISTRITO DE VILA REAL
    # ==========================================
    {"name": "Praia Fluvial de Fornelos", "description": "Praia fluvial com classificação de água balnear em Santa Marta de Penaguião.", "region": "norte", "address": "Santa Marta de Penaguião, Vila Real", "location": {"lat": 41.2167, "lng": -7.7833}, "tags": ["água balnear", "Douro"], "metadata": {"district": "Vila Real", "municipality": "Santa Marta de Penaguião", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial do Rabaçal", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Valpaços.", "region": "norte", "address": "Valpaços, Vila Real", "location": {"lat": 41.6167, "lng": -7.3167}, "tags": ["qualidade ouro", "água balnear", "Valpaços"], "metadata": {"district": "Vila Real", "municipality": "Valpaços", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial de Rebelos", "description": "Praia fluvial com classificação de água balnear em Murça.", "region": "norte", "address": "Murça, Vila Real", "location": {"lat": 41.4000, "lng": -7.4500}, "tags": ["água balnear", "Murça"], "metadata": {"district": "Vila Real", "municipality": "Murça", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Cerva", "description": "Praia fluvial em Ribeira de Pena, num ambiente de montanha.", "region": "norte", "address": "Cerva, Ribeira de Pena, Vila Real", "location": {"lat": 41.5167, "lng": -7.8000}, "tags": ["montanha", "Ribeira de Pena"], "metadata": {"district": "Vila Real", "municipality": "Ribeira de Pena"}},

    # ==========================================
    # DISTRITO DE VISEU
    # ==========================================
    {"name": "Praia Fluvial de Alcafache", "description": "Praia fluvial junto às termas de Alcafache em Mangualde.", "region": "centro", "address": "Alcafache, Mangualde, Viseu", "location": {"lat": 40.6167, "lng": -7.8833}, "tags": ["termas", "Mangualde"], "metadata": {"district": "Viseu", "municipality": "Mangualde"}},
    {"name": "Praia Fluvial do Paraíso", "description": "Praia fluvial com classificação de água balnear em São João do Monte, Tondela.", "region": "centro", "address": "São João do Monte, Tondela, Viseu", "location": {"lat": 40.5333, "lng": -8.1000}, "tags": ["água balnear", "Tondela"], "metadata": {"district": "Viseu", "municipality": "Tondela", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Porto Várzea", "description": "Praia fluvial em Campia, Vouzela.", "region": "centro", "address": "Campia, Vouzela, Viseu", "location": {"lat": 40.7000, "lng": -8.1167}, "tags": ["Vouzela"], "metadata": {"district": "Viseu", "municipality": "Vouzela"}},
    {"name": "Praia Fluvial da Folgosa", "description": "Praia fluvial com qualidade de ouro, acessível a todos e classificação de água balnear em Castro Daire.", "region": "centro", "address": "Castro Daire, Viseu", "location": {"lat": 40.8883, "lng": -7.9057}, "tags": ["qualidade ouro", "acessível", "água balnear", "Castro Daire"], "metadata": {"district": "Viseu", "municipality": "Castro Daire", "certifications": ["Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "40°53'18.2\"N 7°54'20.3\"W"}},
    {"name": "Praia Fluvial da Albufeira do Vilar", "description": "Praia fluvial com classificação de água balnear em Moimenta da Beira.", "region": "centro", "address": "Moimenta da Beira, Viseu", "location": {"lat": 40.9833, "lng": -7.6167}, "tags": ["água balnear", "albufeira", "Moimenta da Beira"], "metadata": {"district": "Viseu", "municipality": "Moimenta da Beira", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial Senhora da Ribeira", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Santa Comba Dão.", "region": "centro", "address": "Pinheiro de Ázere, Santa Comba Dão, Viseu", "location": {"lat": 40.3833, "lng": -8.1333}, "tags": ["qualidade ouro", "água balnear", "Santa Comba Dão"], "metadata": {"district": "Viseu", "municipality": "Santa Comba Dão", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Casal de Sejães", "description": "Praia fluvial com classificação de água balnear em Oliveira de Frades.", "region": "centro", "address": "Oliveira de Frades, Viseu", "location": {"lat": 40.7333, "lng": -8.1667}, "tags": ["água balnear", "Oliveira de Frades"], "metadata": {"district": "Viseu", "municipality": "Oliveira de Frades", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial do Trabulo", "description": "Praia fluvial com classificação de água balnear em Rãs, Sátão.", "region": "centro", "address": "Rãs, Sátão, Viseu", "location": {"lat": 40.7500, "lng": -7.7167}, "tags": ["água balnear", "Sátão"], "metadata": {"district": "Viseu", "municipality": "Sátão", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Carriça", "description": "Praia fluvial com classificação de água balnear em São João da Serra.", "region": "centro", "address": "São João da Serra, Viseu", "location": {"lat": 40.6000, "lng": -7.9000}, "tags": ["água balnear", "Viseu"], "metadata": {"district": "Viseu", "certifications": ["Água Balnear"]}},
    {"name": "Poço Azul", "description": "Praia fluvial selvagem com águas azuis cristalinas em Sabrosa, São Pedro do Sul.", "region": "centro", "address": "Santa Cruz da Trapa, Viseu", "location": {"lat": 40.7811, "lng": -8.1660}, "tags": ["selvagem", "poço", "São Pedro do Sul"], "metadata": {"district": "Viseu", "municipality": "São Pedro do Sul", "gps": "40°46'52.0\"N 8°09'57.9\"W"}},

    # ==========================================
    # DISTRITO DE COIMBRA
    # ==========================================
    {"name": "Praia Fluvial do Rebolim", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro, acessível a todos em Coimbra.", "region": "centro", "address": "Coimbra", "location": {"lat": 40.2167, "lng": -8.4167}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Coimbra"], "metadata": {"district": "Coimbra", "municipality": "Coimbra", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Reconquinho", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Penacova.", "region": "centro", "address": "Penacova, Coimbra", "location": {"lat": 40.2668, "lng": -8.2788}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Penacova"], "metadata": {"district": "Coimbra", "municipality": "Penacova", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "40°16'00.5\"N 8°16'43.8\"W"}},
    {"name": "Praia Fluvial do Vimieiro", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Penacova.", "region": "centro", "address": "Penacova, Coimbra", "location": {"lat": 40.2771, "lng": -8.1981}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Penacova"], "metadata": {"district": "Coimbra", "municipality": "Penacova", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "40°16'37.5\"N 8°11'53.2\"W"}},
    {"name": "Praia Fluvial de Palheiros e Zorro", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Torres do Mondego.", "region": "centro", "address": "Torres do Mondego, Coimbra", "location": {"lat": 40.2500, "lng": -8.3500}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Coimbra"], "metadata": {"district": "Coimbra", "municipality": "Coimbra", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial dos Olhos da Fervença", "description": "Praia fluvial com qualidade de ouro e acessível a todos em Cadima, Cantanhede.", "region": "centro", "address": "Cadima, Cantanhede, Coimbra", "location": {"lat": 40.2833, "lng": -8.6333}, "tags": ["qualidade ouro", "acessível", "água balnear", "Cantanhede"], "metadata": {"district": "Coimbra", "municipality": "Cantanhede", "certifications": ["Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial da Peneda", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Góis.", "region": "centro", "address": "Góis, Coimbra", "location": {"lat": 40.1596, "lng": -8.1106}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Góis"], "metadata": {"district": "Coimbra", "municipality": "Góis", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Canaveias", "description": "Praia fluvial acessível a todos com classificação de água balnear em Góis.", "region": "centro", "address": "Góis, Coimbra", "location": {"lat": 40.1500, "lng": -8.1000}, "tags": ["acessível", "água balnear", "Góis"], "metadata": {"district": "Coimbra", "municipality": "Góis", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Pêgo Escuro", "description": "Praia fluvial acessível a todos com classificação de água balnear em Góis. Uma das mais bonitas da região.", "region": "centro", "address": "Góis, Coimbra", "location": {"lat": 40.1573, "lng": -8.1106}, "tags": ["acessível", "água balnear", "Góis", "pitoresca"], "metadata": {"district": "Coimbra", "municipality": "Góis", "certifications": ["Acessível a Todos", "Água Balnear"], "gps": "40°09'26.3\"N 8°06'38.3\"W"}},
    {"name": "Praia Fluvial da Peneda da Cascalheira", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Secarias, Arganil.", "region": "centro", "address": "Secarias, Arganil, Coimbra", "location": {"lat": 40.2167, "lng": -7.9333}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Arganil"], "metadata": {"district": "Coimbra", "municipality": "Arganil", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Coja", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Arganil.", "region": "centro", "address": "Coja, Arganil, Coimbra", "location": {"lat": 40.2667, "lng": -7.9833}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Arganil"], "metadata": {"district": "Coimbra", "municipality": "Arganil", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Piódão", "description": "Praia fluvial com qualidade de ouro junto à famosa aldeia histórica de Piódão.", "region": "centro", "address": "Piódão, Arganil, Coimbra", "location": {"lat": 40.2296, "lng": -7.8252}, "tags": ["qualidade ouro", "Piódão", "aldeia histórica", "Arganil"], "metadata": {"district": "Coimbra", "municipality": "Arganil", "certifications": ["Qualidade de Ouro"], "gps": "40°13'46.6\"N 7°49'30.7\"W"}},
    {"name": "Praia Fluvial Agroal", "description": "Praia fluvial premiada com Bandeira Azul em Arganil.", "region": "centro", "address": "Arganil, Coimbra", "location": {"lat": 40.2333, "lng": -8.0500}, "tags": ["Bandeira Azul", "água balnear", "Arganil"], "metadata": {"district": "Coimbra", "municipality": "Arganil", "certifications": ["Bandeira Azul", "Água Balnear"]}},
    {"name": "Praia Fluvial Cascata da Fraga da Pena", "description": "Praia fluvial junto a uma espetacular cascata em Arganil. Paisagem deslumbrante.", "region": "centro", "address": "Arganil, Coimbra", "location": {"lat": 40.2500, "lng": -7.9000}, "tags": ["cascata", "Arganil", "paisagem"], "metadata": {"district": "Coimbra", "municipality": "Arganil"}},
    {"name": "Praia Fluvial Nossa Senhora da Piedade", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Lousã.", "region": "centro", "address": "Lousã, Coimbra", "location": {"lat": 40.1117, "lng": -8.2414}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Lousã"], "metadata": {"district": "Coimbra", "municipality": "Lousã", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Bogueira", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Lousã.", "region": "centro", "address": "Lousã, Coimbra", "location": {"lat": 40.1535, "lng": -8.2414}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Lousã"], "metadata": {"district": "Coimbra", "municipality": "Lousã", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"], "gps": "40°09'12.6\"N 8°14'29.2\"W"}},
    {"name": "Praia Fluvial de Avô", "description": "Praia fluvial acessível a todos com classificação de água balnear em Oliveira do Hospital.", "region": "centro", "address": "Avô, Oliveira do Hospital, Coimbra", "location": {"lat": 40.2935, "lng": -7.9027}, "tags": ["acessível", "água balnear", "Oliveira do Hospital"], "metadata": {"district": "Coimbra", "municipality": "Oliveira do Hospital", "certifications": ["Acessível a Todos", "Água Balnear"], "gps": "40°17'36.6\"N 7°54'09.7\"W"}},
    {"name": "Praia Fluvial Alvoco das Várzeas", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Oliveira do Hospital.", "region": "centro", "address": "Alvoco das Várzeas, Oliveira do Hospital, Coimbra", "location": {"lat": 40.3000, "lng": -7.8667}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Oliveira do Hospital"], "metadata": {"district": "Coimbra", "municipality": "Oliveira do Hospital", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Pessegueiro", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Pampilhosa da Serra.", "region": "centro", "address": "Pessegueiro, Pampilhosa da Serra, Coimbra", "location": {"lat": 40.0500, "lng": -7.9333}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Pampilhosa da Serra"], "metadata": {"district": "Coimbra", "municipality": "Pampilhosa da Serra", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Santa Luzia", "description": "Praia fluvial premiada com Bandeira Azul e qualidade de ouro em Pampilhosa da Serra.", "region": "centro", "address": "Pampilhosa da Serra, Coimbra", "location": {"lat": 40.0333, "lng": -7.9500}, "tags": ["Bandeira Azul", "qualidade ouro", "água balnear", "Pampilhosa da Serra"], "metadata": {"district": "Coimbra", "municipality": "Pampilhosa da Serra", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Janeiro de Baixo", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Pampilhosa da Serra.", "region": "centro", "address": "Janeiro de Baixo, Pampilhosa da Serra, Coimbra", "location": {"lat": 40.0167, "lng": -7.9167}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Pampilhosa da Serra"], "metadata": {"district": "Coimbra", "municipality": "Pampilhosa da Serra", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Louçainha", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Penela.", "region": "centro", "address": "Penela, Coimbra", "location": {"lat": 40.0264, "lng": -8.3038}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Penela"], "metadata": {"district": "Coimbra", "municipality": "Penela", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"], "gps": "40°01'35.0\"N 8°18'13.8\"W"}},

    # ==========================================
    # DISTRITO DE CASTELO BRANCO
    # ==========================================
    {"name": "Praia Fluvial Malhadal", "description": "Praia fluvial com classificação de água balnear em Proença-a-Nova.", "region": "centro", "address": "Proença-a-Nova, Castelo Branco", "location": {"lat": 39.7964, "lng": -7.9530}, "tags": ["água balnear", "Proença-a-Nova"], "metadata": {"district": "Castelo Branco", "municipality": "Proença-a-Nova", "certifications": ["Água Balnear"], "gps": "39°47'47.2\"N 7°57'10.8\"W"}},
    {"name": "Praia Fluvial Foz do Cobrão", "description": "Praia fluvial com qualidade de ouro e acessível a todos em Vila Velha de Ródão.", "region": "centro", "address": "Vila Velha de Ródão, Castelo Branco", "location": {"lat": 39.6500, "lng": -7.7000}, "tags": ["qualidade ouro", "acessível", "água balnear", "Tejo"], "metadata": {"district": "Castelo Branco", "municipality": "Vila Velha de Ródão", "certifications": ["Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Unhais da Serra", "description": "Praia fluvial com qualidade de ouro e acessível a todos junto às termas de Unhais da Serra, Serra da Estrela.", "region": "centro", "address": "Unhais da Serra, Covilhã, Castelo Branco", "location": {"lat": 40.2667, "lng": -7.6167}, "tags": ["qualidade ouro", "acessível", "água balnear", "Serra da Estrela", "termas"], "metadata": {"district": "Castelo Branco", "municipality": "Covilhã", "certifications": ["Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Sesmo", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Sesmo.", "region": "centro", "address": "Sesmo, Castelo Branco", "location": {"lat": 40.1000, "lng": -7.5000}, "tags": ["qualidade ouro", "água balnear"], "metadata": {"district": "Castelo Branco", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Ribeira Grande", "description": "Praia fluvial acessível a todos com classificação de água balnear na Sertã.", "region": "centro", "address": "Sertã, Castelo Branco", "location": {"lat": 39.8000, "lng": -8.1000}, "tags": ["acessível", "água balnear", "Sertã"], "metadata": {"district": "Castelo Branco", "municipality": "Sertã", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Açude do Pinto", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Oleiros.", "region": "centro", "address": "Oleiros, Castelo Branco", "location": {"lat": 39.9167, "lng": -7.9167}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Oleiros"], "metadata": {"district": "Castelo Branco", "municipality": "Oleiros", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Aldeia Ruiva", "description": "Praia fluvial acessível a todos com classificação de água balnear em Proença-a-Nova.", "region": "centro", "address": "Proença-a-Nova, Castelo Branco", "location": {"lat": 39.7667, "lng": -7.9333}, "tags": ["acessível", "água balnear", "Proença-a-Nova"], "metadata": {"district": "Castelo Branco", "municipality": "Proença-a-Nova", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Fróia", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Proença-a-Nova.", "region": "centro", "address": "Proença-a-Nova, Castelo Branco", "location": {"lat": 39.7833, "lng": -7.9500}, "tags": ["qualidade ouro", "água balnear", "Proença-a-Nova"], "metadata": {"district": "Castelo Branco", "municipality": "Proença-a-Nova", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Bostelim", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Vila de Rei.", "region": "centro", "address": "Vila de Rei, Castelo Branco", "location": {"lat": 39.6667, "lng": -8.1500}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Vila de Rei"], "metadata": {"district": "Castelo Branco", "municipality": "Vila de Rei", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Zaboeira", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Vila de Rei.", "region": "centro", "address": "Vila de Rei, Castelo Branco", "location": {"lat": 39.6833, "lng": -8.1333}, "tags": ["qualidade ouro", "água balnear", "Vila de Rei"], "metadata": {"district": "Castelo Branco", "municipality": "Vila de Rei", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Albufeira de Meimoa", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Penamacor.", "region": "centro", "address": "Penamacor, Castelo Branco", "location": {"lat": 40.1667, "lng": -7.1667}, "tags": ["qualidade ouro", "água balnear", "albufeira", "Penamacor"], "metadata": {"district": "Castelo Branco", "municipality": "Penamacor", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Troviscal", "description": "Praia fluvial acessível a todos com classificação de água balnear na Sertã.", "region": "centro", "address": "Troviscal, Sertã, Castelo Branco", "location": {"lat": 39.8167, "lng": -8.0833}, "tags": ["acessível", "água balnear", "Sertã"], "metadata": {"district": "Castelo Branco", "municipality": "Sertã", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Lavacolhos", "description": "Praia fluvial acessível a todos com classificação de água balnear no Fundão.", "region": "centro", "address": "Lavacolhos, Fundão, Castelo Branco", "location": {"lat": 40.1500, "lng": -7.5000}, "tags": ["acessível", "água balnear", "Fundão"], "metadata": {"district": "Castelo Branco", "municipality": "Fundão", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Castelo Novo", "description": "Praia fluvial com classificação de água balnear junto à aldeia histórica de Castelo Novo.", "region": "centro", "address": "Castelo Novo, Fundão, Castelo Branco", "location": {"lat": 40.1000, "lng": -7.5167}, "tags": ["água balnear", "aldeia histórica", "Fundão"], "metadata": {"district": "Castelo Branco", "municipality": "Fundão", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial de Janeiro de Cima", "description": "Praia fluvial acessível a todos com classificação de água balnear no Fundão.", "region": "centro", "address": "Janeiro de Cima, Fundão, Castelo Branco", "location": {"lat": 40.0833, "lng": -7.7167}, "tags": ["acessível", "água balnear", "Fundão"], "metadata": {"district": "Castelo Branco", "municipality": "Fundão", "certifications": ["Acessível a Todos", "Água Balnear"]}},

    # ==========================================
    # DISTRITO DA GUARDA
    # ==========================================
    {"name": "Praia Fluvial de Valhelhas", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos na Guarda, junto à Serra da Estrela.", "region": "centro", "address": "Valhelhas, Guarda", "location": {"lat": 40.4167, "lng": -7.4167}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Serra da Estrela"], "metadata": {"district": "Guarda", "municipality": "Guarda", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Aldeia Viçosa", "description": "Praia fluvial acessível a todos com classificação de água balnear em Aldeia Viçosa.", "region": "centro", "address": "Aldeia Viçosa, Guarda", "location": {"lat": 40.5500, "lng": -7.2500}, "tags": ["acessível", "água balnear", "Guarda"], "metadata": {"district": "Guarda", "municipality": "Guarda", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Rapoula do Côa", "description": "Praia fluvial acessível a todos com classificação de água balnear no Sabugal.", "region": "centro", "address": "Rapoula do Côa, Sabugal, Guarda", "location": {"lat": 40.3500, "lng": -7.0833}, "tags": ["acessível", "água balnear", "Sabugal", "Rio Côa"], "metadata": {"district": "Guarda", "municipality": "Sabugal", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial da Devesa", "description": "Praia fluvial acessível a todos com classificação de água balnear no centro do Sabugal.", "region": "centro", "address": "Sabugal, Guarda", "location": {"lat": 40.3500, "lng": -7.0900}, "tags": ["acessível", "água balnear", "Sabugal"], "metadata": {"district": "Guarda", "municipality": "Sabugal", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Lameira-Quadrazais", "description": "Praia fluvial acessível a todos com classificação de água balnear no Sabugal.", "region": "centro", "address": "Quadrazais, Sabugal, Guarda", "location": {"lat": 40.3833, "lng": -7.0500}, "tags": ["acessível", "água balnear", "Sabugal"], "metadata": {"district": "Guarda", "municipality": "Sabugal", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Vale do Rossim", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Gouveia, Serra da Estrela.", "region": "centro", "address": "Gouveia, Guarda", "location": {"lat": 40.4017, "lng": -7.5877}, "tags": ["qualidade ouro", "água balnear", "Serra da Estrela", "Gouveia"], "metadata": {"district": "Guarda", "municipality": "Gouveia", "certifications": ["Qualidade de Ouro", "Água Balnear"], "gps": "40°24'06.3\"N 7°35'15.6\"W"}},
    {"name": "Praia Fluvial Lapa dos Dinheiros", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Seia.", "region": "centro", "address": "Lapa dos Dinheiros, Seia, Guarda", "location": {"lat": 40.4167, "lng": -7.6833}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Seia", "Serra da Estrela"], "metadata": {"district": "Guarda", "municipality": "Seia", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Loriga", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Seia. Uma das mais bonitas da Serra da Estrela.", "region": "centro", "address": "Loriga, Seia, Guarda", "location": {"lat": 40.3273, "lng": -7.6785}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Seia", "Serra da Estrela", "glaciar"], "metadata": {"district": "Guarda", "municipality": "Seia", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "40.327253, -7.678467"}},
    {"name": "Praia Fluvial de Sandomil", "description": "Praia fluvial acessível a todos com classificação de água balnear em Seia.", "region": "centro", "address": "Sandomil, Seia, Guarda", "location": {"lat": 40.3833, "lng": -7.7000}, "tags": ["acessível", "água balnear", "Seia"], "metadata": {"district": "Guarda", "municipality": "Seia", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Covão d'Ametade", "description": "Praia fluvial selvagem num cenário glaciar em Manteigas, Serra da Estrela.", "region": "centro", "address": "Manteigas, Guarda", "location": {"lat": 40.3667, "lng": -7.5833}, "tags": ["selvagem", "glaciar", "Manteigas", "Serra da Estrela"], "metadata": {"district": "Guarda", "municipality": "Manteigas"}},
    {"name": "Praia Fluvial da Relva da Reboleira", "description": "Praia fluvial acessível a todos com classificação de água balnear em Manteigas.", "region": "centro", "address": "Manteigas, Guarda", "location": {"lat": 40.4000, "lng": -7.5333}, "tags": ["acessível", "água balnear", "Manteigas", "Serra da Estrela"], "metadata": {"district": "Guarda", "municipality": "Manteigas", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial da Albufeira do Caldeirão", "description": "Praia fluvial com classificação de água balnear na Guarda.", "region": "centro", "address": "Guarda", "location": {"lat": 40.5333, "lng": -7.2667}, "tags": ["água balnear", "albufeira", "Guarda"], "metadata": {"district": "Guarda", "municipality": "Guarda", "certifications": ["Água Balnear"]}},

    # ==========================================
    # DISTRITO DE LEIRIA
    # ==========================================
    {"name": "Praia Fluvial do Poço da Corga", "description": "Praia fluvial acessível a todos com classificação de água balnear em Castanheira de Pêra.", "region": "centro", "address": "Castanheira de Pêra, Leiria", "location": {"lat": 40.0833, "lng": -8.2000}, "tags": ["acessível", "água balnear", "Castanheira de Pêra"], "metadata": {"district": "Leiria", "municipality": "Castanheira de Pêra", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Aldeia Ana de Aviz", "description": "Praia fluvial com classificação de água balnear em Figueiró dos Vinhos.", "region": "centro", "address": "Figueiró dos Vinhos, Leiria", "location": {"lat": 39.9313, "lng": -8.2865}, "tags": ["água balnear", "Figueiró dos Vinhos"], "metadata": {"district": "Leiria", "municipality": "Figueiró dos Vinhos", "certifications": ["Água Balnear"], "gps": "39.9188217, -8.286556"}},
    {"name": "Praia Fluvial Fragas de São Simão", "description": "Praia fluvial acessível a todos com classificação de água balnear em Figueiró dos Vinhos. Paisagem única das Fragas.", "region": "centro", "address": "Figueiró dos Vinhos, Leiria", "location": {"lat": 39.9154, "lng": -8.3164}, "tags": ["acessível", "água balnear", "Figueiró dos Vinhos", "Fragas"], "metadata": {"district": "Leiria", "municipality": "Figueiró dos Vinhos", "certifications": ["Acessível a Todos", "Água Balnear"], "gps": "39.916333, -8.316417"}},
    {"name": "Praia Fluvial de Mosteiro", "description": "Praia fluvial acessível a todos com classificação de água balnear em Pedrogão Grande.", "region": "centro", "address": "Mosteiro, Pedrogão Grande, Leiria", "location": {"lat": 39.9000, "lng": -8.1500}, "tags": ["acessível", "água balnear", "Pedrogão Grande"], "metadata": {"district": "Leiria", "municipality": "Pedrogão Grande", "certifications": ["Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Cabril", "description": "Praia fluvial com classificação de água balnear em Pedrogão Grande.", "region": "centro", "address": "Cabril, Pedrogão Grande, Leiria", "location": {"lat": 39.9167, "lng": -8.1333}, "tags": ["água balnear", "Pedrogão Grande"], "metadata": {"district": "Leiria", "municipality": "Pedrogão Grande", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Lagoa da Ervedeira", "description": "Praia fluvial com classificação de água balnear em Coimbrão.", "region": "centro", "address": "Coimbrão, Leiria", "location": {"lat": 39.8500, "lng": -8.9667}, "tags": ["água balnear", "lagoa", "Leiria"], "metadata": {"district": "Leiria", "municipality": "Leiria", "certifications": ["Água Balnear"]}},

    # ==========================================
    # DISTRITO DE SANTARÉM
    # ==========================================
    {"name": "Praia Fluvial dos Olhos d'Água", "description": "Praia fluvial junto às nascentes dos Olhos d'Água em Alcanena. Águas cristalinas e temperatura constante.", "region": "centro", "address": "Alcanena, Santarém", "location": {"lat": 39.4444, "lng": -8.7111}, "tags": ["nascente", "águas cristalinas", "Alcanena"], "metadata": {"district": "Santarém", "municipality": "Alcanena", "gps": "39.4443769, -8.7111242"}},
    {"name": "Praia Fluvial do Carvoeiro", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Mação.", "region": "centro", "address": "Carvoeiro, Mação, Santarém", "location": {"lat": 39.6297, "lng": -7.9256}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Mação"], "metadata": {"district": "Santarém", "municipality": "Mação", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"], "gps": "39.6296951, -7.925611"}},
    {"name": "Praia Fluvial de Cardigos", "description": "Praia fluvial com classificação de água balnear em Mação.", "region": "centro", "address": "Cardigos, Mação, Santarém", "location": {"lat": 39.7089, "lng": -8.0162}, "tags": ["água balnear", "Mação"], "metadata": {"district": "Santarém", "municipality": "Mação", "certifications": ["Água Balnear"], "gps": "39.7089313, -8.0162144"}},
    {"name": "Praia Fluvial Aldeia do Mato", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Abrantes.", "region": "centro", "address": "Aldeia do Mato, Abrantes, Santarém", "location": {"lat": 39.5500, "lng": -8.1000}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Abrantes"], "metadata": {"district": "Santarém", "municipality": "Abrantes", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Fontes", "description": "Praia fluvial premiada com Bandeira Azul, qualidade de ouro e acessível a todos em Abrantes.", "region": "centro", "address": "Fontes, Abrantes, Santarém", "location": {"lat": 39.5667, "lng": -8.0833}, "tags": ["Bandeira Azul", "qualidade ouro", "acessível", "água balnear", "Abrantes"], "metadata": {"district": "Santarém", "municipality": "Abrantes", "certifications": ["Bandeira Azul", "Qualidade de Ouro", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Castanheira - Lago Azul", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Ferreira do Zêzere.", "region": "centro", "address": "Castanheira, Ferreira do Zêzere, Santarém", "location": {"lat": 39.7000, "lng": -8.2833}, "tags": ["qualidade ouro", "água balnear", "Lago Azul", "Ferreira do Zêzere"], "metadata": {"district": "Santarém", "municipality": "Ferreira do Zêzere", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Vila Nova-Serra", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Tomar.", "region": "centro", "address": "Vila Nova, Tomar, Santarém", "location": {"lat": 39.6000, "lng": -8.4000}, "tags": ["qualidade ouro", "água balnear", "Tomar"], "metadata": {"district": "Santarém", "municipality": "Tomar", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial de Montes", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear em Tomar.", "region": "centro", "address": "Montes, Tomar, Santarém", "location": {"lat": 39.5833, "lng": -8.3833}, "tags": ["qualidade ouro", "água balnear", "Tomar"], "metadata": {"district": "Santarém", "municipality": "Tomar", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial Agroal - Ourém", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Ourém.", "region": "centro", "address": "Agroal, Ourém, Santarém", "location": {"lat": 39.6791, "lng": -8.4363}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Ourém"], "metadata": {"district": "Santarém", "municipality": "Ourém", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"], "gps": "39.679065, -8.436291"}},

    # ==========================================
    # DISTRITO DE PORTALEGRE (ALENTEJO)
    # ==========================================
    {"name": "Praia Fluvial do Alamal", "description": "Praia fluvial acessível a todos com classificação de água balnear em Gavião, junto ao Rio Tejo.", "region": "alentejo", "address": "Gavião, Portalegre", "location": {"lat": 39.4882, "lng": -7.9684}, "tags": ["acessível", "água balnear", "Rio Tejo", "Gavião"], "metadata": {"district": "Portalegre", "municipality": "Gavião", "certifications": ["Acessível a Todos", "Água Balnear"], "gps": "39°29'17.6\"N 7°58'06.4\"W"}},
    {"name": "Praia Fluvial da Portagem", "description": "Praia fluvial no Rio Sever com vistas para o Castelo de Marvão.", "region": "alentejo", "address": "Portagem, Marvão, Portalegre", "location": {"lat": 39.3829, "lng": -7.3817}, "tags": ["Rio Sever", "Marvão", "castelo"], "metadata": {"district": "Portalegre", "municipality": "Marvão", "gps": "39°22'58.5\"N 7°22'54.3\"W"}},
    {"name": "Praia Fluvial da Barragem de Montargil", "description": "Grande reservatório ideal para desportos aquáticos em Ponte de Sor.", "region": "alentejo", "address": "Montargil, Ponte de Sor, Portalegre", "location": {"lat": 39.0898, "lng": -8.1614}, "tags": ["barragem", "desportos aquáticos", "Ponte de Sor"], "metadata": {"district": "Portalegre", "municipality": "Ponte de Sor", "gps": "39°05'23.3\"N 8°09'41.1\"W"}},
    {"name": "Praia Fluvial da Albufeira do Maranhão", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos em Avis.", "region": "alentejo", "address": "Avis, Portalegre", "location": {"lat": 39.0567, "lng": -7.9114}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Avis"], "metadata": {"district": "Portalegre", "municipality": "Avis", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"], "gps": "39°03'24.2\"N 7°54'41.0\"W"}},

    # ==========================================
    # DISTRITO DE BEJA (ALENTEJO)
    # ==========================================
    {"name": "Praia Fluvial da Tapada Grande", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Mina de São Domingos, Mértola.", "region": "alentejo", "address": "Mina de São Domingos, Mértola, Beja", "location": {"lat": 37.6719, "lng": -7.5054}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Mértola", "antiga mina"], "metadata": {"district": "Beja", "municipality": "Mértola", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Albergaria dos Fusos", "description": "Praia fluvial com classificação de água balnear em Vila Ruiva, Cuba.", "region": "alentejo", "address": "Vila Ruiva, Cuba, Beja", "location": {"lat": 38.2879, "lng": -7.9177}, "tags": ["água balnear", "Cuba"], "metadata": {"district": "Beja", "municipality": "Cuba", "certifications": ["Água Balnear"], "gps": "38°17'16.4\"N 7°55'03.8\"W"}},
    {"name": "Parque Fluvial de Cinco Reis", "description": "Parque fluvial premiado com Bandeira Azul e acessível a todos em Beja.", "region": "alentejo", "address": "Beja", "location": {"lat": 37.9833, "lng": -7.8667}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Beja", "parque"], "metadata": {"district": "Beja", "municipality": "Beja", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Santa Clara", "description": "Praia fluvial premiada com Bandeira Azul na Albufeira de Santa Clara, Odemira.", "region": "alentejo", "address": "Santa Clara-a-Velha, Odemira, Beja", "location": {"lat": 37.5167, "lng": -8.4333}, "tags": ["Bandeira Azul", "água balnear", "albufeira", "Odemira"], "metadata": {"district": "Beja", "municipality": "Odemira", "certifications": ["Bandeira Azul", "Água Balnear"]}},

    # ==========================================
    # DISTRITO DE ÉVORA (ALENTEJO)
    # ==========================================
    {"name": "Praia Fluvial de Monsaraz", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Barragem do Alqueva, com vista para a vila de Monsaraz.", "region": "alentejo", "address": "Monsaraz, Reguengos de Monsaraz, Évora", "location": {"lat": 38.4500, "lng": -7.3833}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Alqueva", "Monsaraz"], "metadata": {"district": "Évora", "municipality": "Reguengos de Monsaraz", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Mourão", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Barragem do Alqueva.", "region": "alentejo", "address": "Mourão, Évora", "location": {"lat": 38.3833, "lng": -7.3500}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Alqueva", "Mourão"], "metadata": {"district": "Évora", "municipality": "Mourão", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Amieira", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Barragem do Alqueva, Portel.", "region": "alentejo", "address": "Amieira, Portel, Évora", "location": {"lat": 38.3000, "lng": -7.5333}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Alqueva", "Portel"], "metadata": {"district": "Évora", "municipality": "Portel", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial Azenhas Del Rei", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Barragem do Alqueva, Alandroal.", "region": "alentejo", "address": "Alandroal, Évora", "location": {"lat": 38.5500, "lng": -7.4000}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Alqueva", "Alandroal"], "metadata": {"district": "Évora", "municipality": "Alandroal", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial de Alqueva", "description": "Praia fluvial premiada com Bandeira Azul e acessível a todos na Barragem do Alqueva, Portel.", "region": "alentejo", "address": "Alqueva, Portel, Évora", "location": {"lat": 38.2167, "lng": -7.5000}, "tags": ["Bandeira Azul", "acessível", "água balnear", "Alqueva", "Portel"], "metadata": {"district": "Évora", "municipality": "Portel", "certifications": ["Bandeira Azul", "Acessível a Todos", "Água Balnear"]}},
    {"name": "Praia Fluvial do Gameiro", "description": "Praia fluvial num parque ecológico em Mora, com área de campismo.", "region": "alentejo", "address": "Mora, Évora", "location": {"lat": 38.9542, "lng": -8.1086}, "tags": ["parque ecológico", "campismo", "Mora"], "metadata": {"district": "Évora", "municipality": "Mora", "gps": "38°57'15.3\"N 8°06'30.8\"W"}},

    # ==========================================
    # DISTRITO DE FARO (ALGARVE)
    # ==========================================
    {"name": "Praia Fluvial Pego do Fundo", "description": "A única praia fluvial oficial do Algarve, acessível a todos com classificação de água balnear em Alcoutim.", "region": "algarve", "address": "Alcoutim, Faro", "location": {"lat": 37.4721, "lng": -7.4768}, "tags": ["acessível", "água balnear", "Alcoutim", "única Algarve"], "metadata": {"district": "Faro", "municipality": "Alcoutim", "certifications": ["Acessível a Todos", "Água Balnear"], "gps": "37°28'19.5\"N 7°28'36.5\"W"}},
    {"name": "Praia Fluvial da Barragem de Odeleite", "description": "Zona de lazer com classificação de água balnear na Barragem de Odeleite, Castro Marim.", "region": "algarve", "address": "Odeleite, Castro Marim, Faro", "location": {"lat": 37.3500, "lng": -7.5000}, "tags": ["água balnear", "barragem", "Castro Marim"], "metadata": {"district": "Faro", "municipality": "Castro Marim", "certifications": ["Água Balnear"]}},
    {"name": "Praia Fluvial da Amoreira", "description": "Praia fluvial com qualidade de ouro e classificação de água balnear onde o rio encontra o mar em Aljezur.", "region": "algarve", "address": "Aljezur, Faro", "location": {"lat": 37.3333, "lng": -8.8500}, "tags": ["qualidade ouro", "água balnear", "Aljezur", "rio e mar"], "metadata": {"district": "Faro", "municipality": "Aljezur", "certifications": ["Qualidade de Ouro", "Água Balnear"]}},
    {"name": "Praia Fluvial de Alte", "description": "Praia fluvial junto à pitoresca aldeia de Alte em Loulé.", "region": "algarve", "address": "Alte, Loulé, Faro", "location": {"lat": 37.2500, "lng": -8.1833}, "tags": ["Alte", "Loulé", "aldeia pitoresca"], "metadata": {"district": "Faro", "municipality": "Loulé"}},

    # ==========================================
    # DISTRITO DE SETÚBAL
    # ==========================================
    {"name": "Praia Fluvial do Samouco", "description": "Praia fluvial em Alcochete, junto ao estuário do Tejo.", "region": "lisboa", "address": "Samouco, Alcochete, Setúbal", "location": {"lat": 38.7333, "lng": -8.9000}, "tags": ["estuário", "Tejo", "Alcochete"], "metadata": {"district": "Setúbal", "municipality": "Alcochete"}},
    {"name": "Praia Fluvial da Saúde", "description": "Praia fluvial em Setúbal junto ao rio Sado.", "region": "lisboa", "address": "Setúbal", "location": {"lat": 38.5167, "lng": -8.8833}, "tags": ["Rio Sado", "Setúbal"], "metadata": {"district": "Setúbal", "municipality": "Setúbal"}},

    # ==========================================
    # MADEIRA
    # ==========================================
    {"name": "Piscinas Naturais de Porto Moniz", "description": "Icónicas piscinas naturais formadas por rocha vulcânica, preenchidas pelas ondas do oceano. Com infraestruturas e nadadores-salvadores.", "region": "madeira", "address": "Porto Moniz, Madeira", "location": {"lat": 32.8667, "lng": -17.1667}, "tags": ["piscinas naturais", "vulcânico", "oceano", "Porto Moniz", "icónico"], "metadata": {"island": "Madeira", "municipality": "Porto Moniz", "type": "piscinas vulcânicas"}},
    {"name": "Piscinas Naturais do Seixal", "description": "Piscinas naturais vulcânicas no Seixal, menos movimentadas que Porto Moniz mas igualmente belas.", "region": "madeira", "address": "Seixal, Madeira", "location": {"lat": 32.8167, "lng": -17.1000}, "tags": ["piscinas naturais", "vulcânico", "Seixal"], "metadata": {"island": "Madeira", "municipality": "Porto Moniz", "type": "piscinas vulcânicas"}},
    {"name": "Doca do Cavacas", "description": "Piscinas naturais de água do mar em Funchal, formadas entre as rochas.", "region": "madeira", "address": "Funchal, Madeira", "location": {"lat": 32.6333, "lng": -16.9333}, "tags": ["piscinas naturais", "Funchal", "rochas"], "metadata": {"island": "Madeira", "municipality": "Funchal", "type": "piscinas naturais"}},
    {"name": "Praia Formosa", "description": "A maior praia natural da Madeira, com seixos escuros e um ambiente atlântico mais agreste.", "region": "madeira", "address": "Funchal, Madeira", "location": {"lat": 32.6333, "lng": -16.9500}, "tags": ["praia", "seixos", "Funchal", "maior"], "metadata": {"island": "Madeira", "municipality": "Funchal", "type": "praia de seixos"}},
    {"name": "Praia de Calheta", "description": "Praia artificial com areia dourada importada, oferecendo águas calmas e protegidas.", "region": "madeira", "address": "Calheta, Madeira", "location": {"lat": 32.7167, "lng": -17.1833}, "tags": ["praia", "areia", "Calheta", "artificial"], "metadata": {"island": "Madeira", "municipality": "Calheta", "type": "praia artificial"}},

    # ==========================================
    # AÇORES
    # ==========================================
    {"name": "Poça da Dona Beija", "description": "Famosas piscinas naturais de água termal quente em São Miguel. Ambiente noturno único.", "region": "acores", "address": "Furnas, São Miguel, Açores", "location": {"lat": 37.7667, "lng": -25.3167}, "tags": ["termal", "água quente", "Furnas", "São Miguel", "noturno"], "metadata": {"island": "São Miguel", "municipality": "Povoação", "type": "piscinas termais"}},
    {"name": "Praia Fluvial da Lomba da Fazenda", "description": "Uma das raras praias fluviais dos Açores, junto a nascentes de água doce em São Miguel.", "region": "acores", "address": "Lomba da Fazenda, São Miguel, Açores", "location": {"lat": 37.8333, "lng": -25.2000}, "tags": ["praia fluvial", "água doce", "São Miguel", "rara"], "metadata": {"island": "São Miguel", "type": "praia fluvial"}},
    {"name": "Lagoa do Fogo", "description": "Deslumbrante lagoa de origem vulcânica na cratera de um vulcão em São Miguel. Banhos permitidos com cuidado.", "region": "acores", "address": "Lagoa do Fogo, São Miguel, Açores", "location": {"lat": 37.7500, "lng": -25.4667}, "tags": ["lagoa", "vulcânico", "cratera", "São Miguel"], "metadata": {"island": "São Miguel", "type": "lagoa vulcânica"}},
]

async def seed_piscinas():
    """Populate the database with Piscinas/Praias Fluviais data"""
    print("🏊 A popular base de dados com Praias Fluviais e Piscinas Naturais de Portugal...")

    # Delete existing piscinas items
    result = await db.heritage_items.delete_many({"category": "piscinas"})
    print(f"   Removidos {result.deleted_count} itens existentes da categoria piscinas")

    # Insert new items
    items_to_insert = []
    for praia in PISCINAS_DATA:
        item = {
            "id": str(uuid.uuid4()),
            "name": praia["name"],
            "description": praia["description"],
            "category": "piscinas",
            "subcategory": praia.get("subcategory"),
            "region": praia["region"],
            "location": praia.get("location"),
            "address": praia.get("address"),
            "image_url": praia.get("image_url"),
            "tags": praia.get("tags", []),
            "related_items": [],
            "metadata": praia.get("metadata", {}),
            "created_at": datetime.now(timezone.utc)
        }
        items_to_insert.append(item)

    if items_to_insert:
        await db.heritage_items.insert_many(items_to_insert)
        print(f"   ✅ Inseridos {len(items_to_insert)} itens de Praias Fluviais e Piscinas Naturais")

    # Count items by region
    print("\n📊 Distribuição por região:")
    regions = ["norte", "centro", "alentejo", "algarve", "lisboa", "madeira", "acores"]
    for region in regions:
        count = await db.heritage_items.count_documents({"category": "piscinas", "region": region})
        if count > 0:
            print(f"   - {region.capitalize()}: {count} praias")

    # Total count
    total = await db.heritage_items.count_documents({"category": "piscinas"})
    print(f"\n   📊 Total de Praias Fluviais na base de dados: {total}")

    print("\n✅ Base de dados populada com sucesso!")

if __name__ == "__main__":
    asyncio.run(seed_piscinas())
